import {

  printers1,
  printers2,
  printers4,
  printers5,
  printers6,
  printers7,
  printers8,
  printers9,
  inkjet1,
  inkjet2,
  inkjet3,
  inkjet4,
  ribban1,
  ribban2,
  ribban3,
  ribban4,
  Catridges1,
  Catridges2,
  Catridges3,
  Catridges4,
  
} from "../assets/images/index1";
import{pdf1,
  PRINTER_PANTUM_CP2200DW,
  PRINTER_PANTUM_BM5100FDW,
  PRINTER_PANTUM_M6609N,
  PRINTER_PANTUM_P3300DN,
  PRINTER_PANTUM_P3300DW,
  PRINTER_PANTUM_P2509W,
  PRINTER_PANTUM_BP5100DN,
  PRINTER_PANTUM_M6559N,
  PRINTER_PANTUM_P2509,
  hp1,
  hp2,
  hp3,
  ricoh1,
  ricoh2,
  ricoh3,
  ricoh4,
  ricoh5,
  espson1,
  espson2,} from "../assets/images/index"

import "./style.css";


export const SplOfferData = [{
  productName: "Hat",
  brand: "MAJIK",
  price: 288,
  id: 1,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-cap.png",
  rating: "3.6",
},
{
  productName: "Plain Round Neck T-shirt",
  brand: "Huetrap",
  price: 395,
  id: 2,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-fit-t-shirt.png",
  rating: "4.1",
},
{
  productName: "Cotton Hoodie",
  brand: "Scott International",
  price: 498,
  id: 3,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-hoodie.png",
  rating: "3.8",
},
{
  productName: "Men's Waistcoat",
  brand: "LEVIS",
  price: 2500,
  id: 4,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-jacket.png",
  rating: "4.3",
},
{
  productName: "Slim Fit Jeans",
  brand: "LEVIS",
  price: 1469,
  id: 5,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-jeans-pants.png",
  rating: "3.1",
},
{
  productName: "Miss Chase Bodycon Dress",
  brand: "LEVIS",
  price: 974,
  id: 6,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-modren-net.png",
  rating: "3.8",
},
{
  productName: "Zari Design Kurta",
  brand: "Libas",
  price: 1869,
  id: 7,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-punjabi.png",
  rating: "4.4",
},
{
  productName: "Slim Fit Blazer",
  brand: "LEVIS",
  price: 2599,
  id: 8,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-purple-jacket.png",
  rating: "4.2",
},
{
  productName: "Animal Printed Shirt",
  brand: "Mufti",
  price: 1017,
  id: 9,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-short-sleeves-shirt.png",
  rating: "4",
},
{
  productName: "Polyester Saree",
  brand: "Ahalyaa",
  price: 419,
  id: 10,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-side-sareee.png",
  rating: "3.8",
},
{
  productName: "Warm Up Jacket",
  brand: "Monte Carlo",
  price: 2796,
  id: 11,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-sim-jacket.png",
  rating: "4.4",
},
{
  productName: "Wrap Dress",
  brand: "Vero Moda",
  price: 3039,
  id: 12,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-simple-formal.png",
  rating: "3.2",
},
{
  title: "Knit Cream Sweater",
  brand: "MansiCollections",
  price: 996,
  id: 13,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-stylish-sweater.png",
  rating: "3.2",
},
{
  title: "Sheer Anarkali",
  brand: "Saadgi",
  price: 2172,
  id: 14,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-white-punjabi.png",
  rating: "3.2",
},
{
  title: "Embellished Maxi Dress",
  brand: "STREET 9",
  price: 1799,
  id: 15,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/cloths-blue-fork.png",
  rating: "3.2",
},
{
  title: "Embroidered Net Gown",
  brand: "Manyavar",
  price: 62990,
  id: 16,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/cloths-long-fork.png",
  rating: "3.2",
},
{
  title: "Analog Men's Watch",
  brand: "Fastrack",
  price: 1850,
  id: 25,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/electronics-casual-watch.png",
  rating: "4.2",
},
{
  title: "Tea Kettle Pot",
  brand: "Indian Art Villa",
  price: 1685,
  id: 26,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/electronics-copper-kettle.png",
  rating: "3.8",
},
{
  title: "Aluminium 4 Cup Tea Kettle",
  brand: "Kitchen Expert",
  price: 399,
  id: 27,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/electronics-kettle.png",
  rating: "4.3",
},
{
  title: "Tripod Stand",
  brand: "Sketchfab",
  price: 390,
  id: 28,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/electronics-medium-tripod.png",
  rating: "4.2",
},
{
  title: "Beard Trimmer",
  brand: "Nova",
  price: 398,
  id: 29,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/electronics-nova-trimmer.png",
  rating: "4.5",
},
{
  productName: "Nova SuperGroom Multi-kit",
  brand: "Nova",
  price: 1199,
  id: 30,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/electronics-nover-v2-trimmer.png",
  rating: "4.4",
},
{
  productName: "Privateer Quartz Watch",
  brand: "Fossil",
  price: 8122,
  id: 31,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/electronics-royal-black-watch.png",
  rating: "4.4",
},
{
  productName: "Chronograph black Watch",
  brand: "Fossil",
  price: 6395,
  id: 32,
  image_url:
    "https://assets.ccbp.in/frontend/react-js/ecommerce/electronics-royal-watch.png",
  rating: "3.8",
},];

export const paginationItems = [
  {
    _id: "hp1",
    img: hp1,
    productName:
      "PRINTER HP JET D'ENCRE HP SMART TANK 516 COULEUR MFP 3EN1 A4 WIFI",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Hp",
    des: "Desc :PRINTER Jet HP SMART TANK 516 3en1 Couleur 3YW70A - Fonction: Impression, Copie, Numérisation - Technologie d'impression: jet d'encre - Vitesse d'impression Noir : Jusqu'à 22 ppm - Vitesse d’impression Couleur : Jusqu'à 16 ppm - Résolution d'impression Couleur : 1200x1200dpi - Format Papier : A4 - Capacité Papier : 100 feuilles -  Cycle d'utilisation (mensuel, A4) : Jusqu'à 1000pages - Connectivité: USB 2.0 haute vitesse, Wi-Fi, Bluetooth LE -  Dimensions: 447 x 373 x 158 mm - Garantie: 1 an",
    cast: "PRINTER",
    pdf: pdf1,
   
  },

  {
    _id: "hp2",
    img: hp2,
    productName: "Printers HP INK TANK WIRELESS 415 ALL-IN-ONE",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Hp",
    des: "Desc : PRINTER Multifonction Jet d'encre 3 en 1 à réservoir intégré - Impression, numérisation, copie, sans fil - Résolution d'impression: Jusqu'à 4800 x 1200 dpi - Vitesse d'impression Couleur Jusqu'à 15 ppm -Vitesse d'impression N et B Jusqu'à 18 ppm - Résolution du scanner: 1200 x 1200 dpi - Format A4 - Interface USB - Bac d'alimentation de 60 feuilles - Dimensions: 525 x 310 x 158 mm - Garantie 1 an (+ Extension de Garantie 2 Ans ) + 5 Bouteilles",
    cast: "PRINTER",
    pdf: pdf1,
    // ficheTech: [],
  },

  {
    _id: "hp3",
    img: hp3,
    productName: "PRINTER HP INK TANK WIRELESS 415 ALL-IN-ONE",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Hp",
    des: "PRINTER à Reservoir printer HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
    cast: "PRINTER",
    pdf: pdf1,
    
  },
 
  {
    _id: "ricoh1",
    img: ricoh1,
    productName: "PRINTER RICOH P501",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Ricoh",
    des: "PRINTER is a Reservoir integer HP Ink Tank 315 - Fonctions: Impression, copier, Numerisation - Format Paper: A4 - Technologie d'impression: jet d'encre thermique HP - with : Just 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
    cast: "PRINTER",
   
  },

  {
    _id: "ricoh2",
    img: ricoh2,
    productName: "PRINTER RICOH SP3710DN",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Ricoh",
    des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - within impression: Just19 p  pm (Noir), Just'a 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
    cast: "PRINTER",
    pdf: pdf1,
   
  },
  {
    _id: "ricoh3",
    img: ricoh3,
    productName: "PRINTER RICOH SP4520DN",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Ricoh",
    des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
    cast: "Imprimante",
    pdf: pdf1,
    
  },
  {
    _id: "ricoh4",
    img: ricoh4,
    productName: "PRINTER RICOH COULEUR LASER SPC840",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Ricoh",
    des: "PRINTER capacite HP Ink Tank 305 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
    cast: "PRINTER",
    pdf: pdf1,
    
  },
  {
    _id: "ricoh5",
    img: ricoh5,
    productName: "PRINTER RICOH SP4510DN (407313)",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Ricoh",
    des: "PRINTER capacite HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
    cast: "PRINTER",
  
    
  },

 

  {
    _id: "espson1",
    img: espson1,
    productName: "PRINTER EPSON L3251 3EN1 A4 WIFI",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Epson",
    des: "PRINTER is a Reservoir integreate HP Ink Tank 315 - Fonctions: Impression, copier, Numerisation - Format Papier: A4 - Multi colour printer: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
    cast: "PRINTER",
    
   
  },

  {
    _id: "espson2",
    img: espson2,
    productName: "PRINTERE EPSON JET D'ENCRE L3156 COULEUR A4  WIFI",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Epson",
    des: "PRINTER  HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie : jet d'encre thermique HP - Multi colour printer: Just 19 ppm (black), Just a 15 ppm (colour) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
    cast: "PRINTER",
       
  },
  {
    _id: "201",
    img:  PRINTER_PANTUM_CP2200DW,
    productName: "Printer PANTUM CP2200DW",
    price: "3500.00",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "IPRINTER Laser PANTUM Couleur - Fonctions: Impression  - Technologie d'impression: Laser - Format Papier: A4 - Vitesse d’impression(Couleur/N&B): 24 ppm (A4) / 26 ppm (Lettre) - Résolution d'impression: 600 x 600 dpi - Sortie papier: 100 page - Mémoire: Double cœur, 1 GHz - Impression recto verso: Automatique - Heure de la première impression: Moins de 11s  - Connecteurs: USB 2.0 haut débit Ethernet 10/100/1000 BaseTX (RJ-45) 802.11b/g/n Sans fil - Dimensions: 411.2 x 394.1 x 243.7mm - Poids: 16,1 kg - Couleur: Blanc",
    cast: "PRINTER",
   
    DATA: [
      { label: "Technology ", value: "Electrophotographic monochrome laser " },
      { label: "Print speed ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Maximum Monthly Duty Cycle", value: "15,000 pages " },
      {
        label: "Recommended monthly volume Resolution(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
  },
  {
    _id: "202",
    img:  PRINTER_PANTUM_BM5100FDW,
    productName: "PRINTER PANTUM BM5100FDW",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "Pantum BM5100fdw Imprimante laser mono : Pantum BM5100fdw -Imprimante :laser -monochrome multifonction,:format A4-,4-en-1 avec fonctions impression, copie, numérisation et fax, vitesse d'impression de 40ppm, connexion Réseau :LAN RJ45-, Wifichrome multifonction, format A4, 4-en-1 avec fonctions impression, copie, numérisation et fax, vitesse d'impression de 40ppm, connexion Réseau LAN RJ45, Wifi",
    cast: "Imprimante",
    DATA: [
      { label: "Technology ", value: "Electrophotographic monochrome laser " },
      { label: "Print speed ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Maximum Monthly Duty Cycle", value: "15,000 pages " },
      {
        label: "Recommended monthly volume Resolution(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
    
   
  },
  {
    _id: "203",
    img:  PRINTER_PANTUM_BP5100DN,
    productName: "PRINTER PANTUM BP5100DN",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "PRINTER Monochrome Laser PANTUM BP5100DN : Suitable for the enviorment -: - processer is 1,2 GHz - Dimensions: 364 x 344 x 257 mm - Poids: 9.3 kg - Garantee: 1 an",
    cast: "PRINTER",
    DATA: [
      { label: "Technology ", value: "Electrophotographic monochrome laser " },
      { label: "Print speed ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Maximum Monthly Duty Cycle", value: "15,000 pages " },
      {
        label: "Recommended monthly volume Resolution(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
    
  },
  {
    _id: "2005",
    img:  PRINTER_PANTUM_M6609N,
    productName: "PRINTER PANTUM M6559N",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "PRINTER Laser IN A toner rechargeable PANTUM M6559N - Capacite of impression just  1600 pages - with d0 impression : 22 ppm (A4) / 23 ppm (Lettre) - Résolution (impression, copie et numérisation) : 1200×1200dpi - Heure de la première impression : Moins de 7.8s - Connectivité : USB 2.0 haute vitesse - Vitesse de copie : 22cpm (A4) / 23cpm (Lettre) - Capacité du chargeur automatique de documents : 35 pages - Entrée papier : 150 pages - Sortie papier : 100 pages - Dimensions : 417 x 305 x 301 mm - Poids : 8.5 kg - Garantie 1 an",
    cast: "PRINTER",
    DATA: [
      { label: "Technology ", value: "Electrophotographic monochrome laser " },
      { label: "Print speed ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Maximum Monthly Duty Cycle", value: "15,000 pages " },
      {
        label: "Recommended monthly volume Resolution(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
  },

  {
    _id: "205",
    img:  PRINTER_PANTUM_M6559N,
    productName: "PRINTER PANTUM M6559N",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "PRINTERLaser capcite of toner rechargeable PANTUM M6559N - Capacite of Just  1600 pages - Vitesse d’impression : 22 ppm (A4) / 23 ppm (Lettre) - Résolution (impression, copie et numérisation) : 1200×1200dpi - Heure de la première impression : Moins de 7.8s - Connectivité : USB 2.0 haute vitesse - Vitesse de copie : 22cpm (A4) / 23cpm (Lettre) - Capacité du chargeur automatique de documents : 35 pages - Entrée papier : 150 pages - Sortie papier : 100 pages - Dimensions : 417 x 305 x 301 mm - Poids : 8.5 kg - Garantie 1 an",
    cast: "PRINTER",
    DATA: [
      { label: "Technology ", value: "Electrophotographic monochrome laser " },
      { label: "Print speed ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Maximum Monthly Duty Cycle", value: "15,000 pages " },
      {
        label: "Recommended monthly volume Resolution(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
  },

  {
    _id: "206",
    img:  PRINTER_PANTUM_P3300DN,
    productName: "PRINTER PANTUM P3300DN",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "PRINTERLaser PANTUM P3300DN - Fonctions: Impression - Technologie description 'impression: Laser - Format Paper: A4-A5 - Vitesse d’impression: 33 ppm (A4) / 35 ppm (Lettre) - Résolution d'impression: Jusqu'à 1200 x 1200 ppp - Papier Bac d'alimentation: 250 pages - Sortie papier: 150 page - Mémoire: 256 Mo - Impression recto verso: Automatique - Heure de la première impression: Moins de 8.2s  - Taille du support: A4, A5, JIS B5, IS0 B5, A6, Lettre, Légal, Exécutif, Folio, Oficio, Déclaration, Carte postale japonaise, ZL, Big 16K, Big 32K, 16K, 32K, B6， Yougata4, Carte postale, Younaga3, Nagagata3, Yougata2 - Connecteurs: USB2.0 haut débit / Ethernet：IEEE 802.3 10/100Base-Tx - Dimensions: 354 x 334 x 232mm - Poids: 6,8 kg - Couleur: Blanc",
    cast: "PRINTER",
    DATA: [
      { label: "Technology ", value: "Electrophotographic monochrome laser " },
      { label: "Print speed ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Maximum Monthly Duty Cycle", value: "15,000 pages " },
      {
        label: "Recommended monthly volume Resolution(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
  },

  {
    _id: "207",
    img: PRINTER_PANTUM_P3300DW,
    productName: "PRINTER PANTUM P3300DW",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "PRINTER Laser PANTUM P3300DW - Fonctions: Impression - Technologies do bestimpression: Laser - Format Papier: A4-A5 - Vitesse d’impression: 33 ppm (A4) / 35 ppm (Lettre) - Résolution d'impression: Jusqu'à 1200 x 1200 ppp - Papier Bac d'alimentation: 250 pages - Sortie papier: 150 page - Mémoire: 256 Mo - Impression recto verso: Automatique - Heure de la première impression: Moins de 8.2s - Interface: Ethernet USB 2.0 haut débit : Wi-Fi IEEE 802.3 10/100Base-Tx : IEEE 802.11b/g/n - Connecteurs: USB ; WIFI - Dimensions: 354 x 334 x 232mm - Poids: 6,8 kg - Couleur: Blanc",
    cast: "PRINTER",
    DATA: [
      { label: "Technology ", value: "Electrophotographic monochrome laser " },
      { label: "Print speed ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Maximum Monthly Duty Cycle", value: "15,000 pages " },
      {
        label: "Recommended monthly volume Resolution(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
  },

  {
    _id: "208",
    img:  PRINTER_PANTUM_P2509W,
    productName: "IPRINTER PANTUM P2509W",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "PRINTER Laser PANTUM P2509W - Fonctions: Impression - Technologie: Laser - Format Papier: A4 - impression: 22 ppm (A4) / 23 ppm (Lettre) - Résolution d'impression: Jusqu'à 1200 x 1200 ppp - Entrée papier: de 150 feuilles - Sortie papier: 100 page - Mémoire: 128 Mo - Impression recto verso: Manuel - Heure de la première impression: Moins de 7.8s - Taille du support: A4, A5, A6, JIS B5, ISO B5, B6, Lettre, Légal, Exécutif, Déclaration, Enveloppe Monarch, Enveloppe DL, enveloppe C5, enveloppe C6, enveloppe NO.10, carte postale japonaise, Folio, Oficio, Grand 16k, 32k, 16k, Grand 32k, ZL,Yougata4, Carte postale, Younaga3, Nagagata3, Yougata2 - Toner rechargeable - Connecteurs: USB 2.0 ; Wi-Fi - Dimensions: 337 x 220 x 178 mm - Poids: 4,75 kg - Couleur: Blanc.",
    cast: "PRINTER",
    DATA: [
      { label: "Technology ", value: "Electrophotographic monochrome laser " },
      { label: "Print speed ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Maximum Monthly Duty Cycle", value: "15,000 pages " },
      {
        label: "Recommended monthly volume Resolution(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
  },
  {
    _id: "233",
    img:  PRINTER_PANTUM_P2509,
    productName: "PRINTER PANTUM P2509",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "PRINTER Laser PANTUM P2509 - Fonctions Impression - Capacite of impression Just :1600 pages - Formats papier: A4 - Technologie d’impression Laser Monochrome - Vitesse d’impression Noir & Blanc: Jusqu’à 22 pages par minute en A4 - Résolution: 1200 dpi - Mémoire: 128 Mo - Connectivité: USB 2.0 - Dimensions: 337 x 220 x 178 mm - Poids: 4.75 kg - Toner recheargeable - Garantie: 1 an",
    cast: "PRINTER",
    DATA: [
      { label: "Technology ", value: "Electrophotographic monochrome laser " },
      { label: "Print speed ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Maximum Monthly Duty Cycle", value: "15,000 pages " },
      {
        label: "Recommended monthly volume Resolution(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
   
  },
  {
    _id: "220",
    img: Catridges3,
    productName: " ink storage ",
    price: "375.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cast: "catridges",
    DATA: [
      { label: "Technology ", value: "Electrophotographic monochrome laser " },
      { label: "Print speed ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Maximum Monthly Duty Cycle", value: "15,000 pages " },
      {
        label: "Recommended monthly volume Resolution(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
  },
  {
    _id: "221",
    img: Catridges4,
    productName: "Bac de dechet",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cast: "Bac",
    DATA: [
      { label: "Technology ", value: "Electrophotographic monochrome laser " },
      { label: "Print speed ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Maximum Monthly Duty Cycle", value: "15,000 pages " },
      {
        label: "Recommended monthly volume Resolution(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
  },
  {
    _id: "215",
    img: ribban3,
    productName: "Ribban",
    price: "450.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cast: "Ruban",
    DATA: [
      { label: "Technology ", value: "Electrophotographic monochrome laser " },
      { label: "Print speed ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Maximum Monthly Duty Cycle", value: "15,000 pages " },
      {
        label: "Recommended monthly volume Resolution(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
  },
  {
    _id: "216",
    img: ribban4,
    productName: "Ribban",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cast: "Ruban",
    DATA: [
      { label: "Technology ", value: "Electrophotographic monochrome laser " },
      { label: "Print speed ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Maximum Monthly Duty Cycle", value: "15,000 pages " },
      {
        label: "Recommended monthly volume Resolution(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
  },
  {
    _id: "209",
    img: inkjet1,
    productName: "inkjet",
    price: "345.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cast: "Encre",
  },
  {
    _id: "210",
    img: inkjet2,
    productName: "inkjet",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cast: "Encre",
  },

  {
    _id: "211",
    img: inkjet3,
    productName: "inkjet",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cast: "Encre",
    DATA: [
      { label: "Technology ", value: "Electrophotographic monochrome laser " },
      { label: "Print speed ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Maximum Monthly Duty Cycle", value: "15,000 pages " },
      {
        label: "Recommended monthly volume Resolution(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
  },
  {
    _id: "212",
    img: inkjet4,
    productName: "inkjet",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cast: "Ink Jet tool",
    DATA: [
      { label: "Technology ", value: "Electrophotographic monochrome laser " },
      { label: "Print speed ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Maximum Monthly Duty Cycle", value: "15,000 pages " },
      {
        label: "Recommended monthly volume Resolution(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
  },
  {
    _id: "213",
    img: ribban1,
    productName: "Ribban Printer A",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cast: "Ruban",
    DATA: [
      { label: "Technology ", value: "Electrophotographic monochrome laser " },
      { label: "Print speed ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Maximum Monthly Duty Cycle", value: "15,000 pages " },
      {
        label: "Recommended monthly volume Resolution(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
  },
  {
    _id: "214",
    img: ribban2,
    productName: "Ribban Printer B",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cast: "Ruban",
    DATA: [
      { label: "Technology ", value: "Electrophotographic monochrome laser " },
      { label: "Print speed ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Maximum Monthly Duty Cycle", value: "15,000 pages " },
      {
        label: "Recommended monthly volume Resolution(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
  },

  {
    _id: "217",
    img: Catridges1,
    productName: "Catridges ut6",
    price: "450.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cast: "Bac",
  },
  {
    _id: "219",
    img: Catridges2,
    productName: "Catridges 123P",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cast: "Catridges",
  },

  // =================== imprimante hp =================

 
  {
    _id: "201",
    img: printers1,
    productName: "printers",
    price: "305.00",
    color: "Blank and White",
    badge: true,
    des: " basically an output device which prints a hard copy of the electronic data that is stored in the computer or any other devices.",
    cast: "printers",
  },
  {
    _id: "202",
    img: printers2,
    productName: "Printer",
    price: " 1800.00",
    color: "Gray",
    badge: true,
    des: " basically an output device which prints a hard copy of the electronic data that is stored in the computer or any other devices.",
    cast: "printers",
  },
  {
    _id: "203",
    img: printers4,
    productName: "printers",
    price: "225.00",
    color: "Mixed",
    badge: true,
    des: " basically an output device which prints a hard copy of the electronic data that is stored in the computer or any other devices.",
    cast: "printers",
  },
  {
    _id: "204",
    img: printers5,
    productName: "printers",
    price: "220.00",
    color: "Black",
    badge: true,
    des: " basically an output device which prints a hard copy of the electronic data that is stored in the computer or any other devices.",
    cast: "printers",
  },
  {
    _id: "205",
    img: printers6,
    productName: "printers",
    price: "105.00",
    color: "Mixed",
    badge: true,
    des: " basically an output device which prints a hard copy of the electronic data that is stored in the computer or any other devices.",
    cast: "printers",
  },
  {
    _id: "206",
    img: printers7,
    productName: "printers",
    price: "220.00",
    color: "Black",
    badge: true,
    des: " basically an output device which prints a hard copy of the electronic data that is stored in the computer or any other devices.",
    cast: "imprimante",
  },
  {
    _id: "207",
    img: printers8,
    productName: "printers",
    price: "85.00",
    color: "Mixed",
    badge: true,
    des: " basically an output device which prints a hard copy of the electronic data that is stored in the computer or any other devices.",
    cast: "printers",
  },
  {
    _id: "208",
    img: printers9,
    productName: "printers",
    price: "220.00",
    color: "Black",
    badge: true,
    des: " basically an output device which prints a hard copy of the electronic data that is stored in the computer or any other devices.",
    cast: "printers",
  },
  {
    _id: "209",
    img: inkjet1,
    productName: "inkjet",
    price: "175.00",
    color: "Mixed",
    badge: true,
    des: " A computer peripheral that produces hard copies of a text document or photo by spraying droplets of ink onto paper.",
    cast: "printer inkjet",
  },
  {
    _id: "210",
    img:inkjet2 ,
    productName: " Printer ink ",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "A computer peripheral that produces hard copies of a text document or photo by spraying droplets of ink onto paper.",
    cast: "printer inkjet",
  },
  {
    _id: "211",
    img: inkjet3,
    productName: "printer inkjet",
    price: "95.00",
    color: "Mixed",
    badge: true,
    des: "A computer peripheral that produces hard copies of a text document or photo by spraying droplets of ink onto paper.",
    cast: "aprinter inkjet",
  },
  {
    _id: "212",
    img: inkjet4,
    productName: " printer inkjet",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "A computer peripheral that produces hard copies of a text document or photo by spraying droplets of ink onto paper.",
    cast: "inkjet ",
  },
  {
    _id: "213",
    img:  ribban1,
    productName: "Ribban printer",
    price: "440.00",
    color: "Mixed",
    badge: true,
    des: "device that accepts text and graphic output from a computer and transfers,  the information to paper, usually to standard-size, 8.5 by 11 sheets of paper",
    cast: "Ribban printer",
  },
  {
    _id: "214",
    img:  ribban2,
    productName: "Ribban printer",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "device that accepts text and graphic output from a computer and transfers,  the information to paper.",
    cast: "Ribban printer",
  },
  {
    _id: "215",
    img: ribban3,
    productName: "Ribban printer",
    price: "125.00",
    color: "Mixed",
    badge: true, 
    des: "device that accepts text and graphic output from a computer and transfers,  the information to paper.",
    cast: "Ribban printer",
  },
  {
    _id: "216",
    img:  ribban4,
    productName: "Ribban printer",
    price: "220.00",
    color: "Black",
    badge: true, 
    des: "device that accepts text and graphic output from a computer and transfers,  the information to paper.",
    cast: "Ribban printer",
  },
  {
    _id: "217",
    img: Catridges1,
    productName: "Lexmark Toner Kit",
    price: "250.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cast: "Toner Kit",
  },
  {
    _id: "219",
    img: Catridges2,
    productName: "Toner Catridges",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cast: "Toner Catridges",
  },
  {
    _id: "220",
    img: Catridges3,
    productName: " lexmark Toner Catridges",
    price: "125.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cast: "Bac",
  },
  {
    _id: "221",
    img: Catridges4,
    productName: "Toner return Catridges",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cast: "Bac",
  },
  {
    productName: "Hat",
    brand: "MAJIK",
    price: 288,
    id: 1,
    img:
      "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-cap.png",
    rating: "3.6",
  },
  {
    productName: "Plain Round Neck T-shirt",
    brand: "Huetrap",
    price: 395,
    id: 2,
    img:
      "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-fit-t-shirt.png",
    rating: "4.1",
  },
  {
    productName: "Cotton Hoodie",
    brand: "Scott International",
    price: 498,
    id: 3,
    img:
      "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-hoodie.png",
    rating: "3.8",
  },
  {
    productName: "Men's Waistcoat",
    brand: "LEVIS",
    price: 2500,
    id: 4,
    img:
      "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-jacket.png",
    rating: "4.3",
  },
  {
    productName: "Slim Fit Jeans",
    brand: "LEVIS",
    price: 1469,
    id: 5,
    img:
      "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-jeans-pants.png",
    rating: "3.1",
  },
  {
    productName: "Miss Chase Bodycon Dress",
    brand: "LEVIS",
    price: 974,
    id: 6,
    img:
      "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-modren-net.png",
    rating: "3.8",
  },
  {
    productName: "Zari Design Kurta",
    brand: "Libas",
    price: 1869,
    id: 7,
    img:
      "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-punjabi.png",
    rating: "4.4",
  },
  {
    productName: "Slim Fit Blazer",
    brand: "LEVIS",
    price: 2599,
    id: 8,
    img:
      "https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-purple-jacket.png",
    rating: "4.2",
  },

];
